FROM openjdk:17-jdk-slim

ARG PORT
ARG MONGO_URI
ARG MONGO_DATA_BASE

ENV PORT=${PORT}
ENV MONGO_URI=${MONGO_URI}
ENV MONGO_DATA_BASE=${MONGO_DATA_BASE}

COPY target/*.jar app.jar
EXPOSE ${PORT}
ENTRYPOINT ["java","-jar","/app.jar"]